# Generated by Django 2.0 on 2018-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordination',
            name='construction_paper',
        ),
        migrations.RemoveField(
            model_name='coordination',
            name='design_material',
        ),
        migrations.RemoveField(
            model_name='coordination',
            name='design_paper',
        ),
        migrations.RemoveField(
            model_name='coordination',
            name='material_usage',
        ),
        migrations.AddField(
            model_name='coordination',
            name='construction_paper_paths',
            field=models.FileField(blank=True, upload_to='', verbose_name='施工图纸文件路径'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='design_material_paths',
            field=models.FileField(blank=True, upload_to='', verbose_name='设计材料单文件路径'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='design_paper_paths',
            field=models.CharField(blank=True, max_length=100, verbose_name='设计图纸文件路径'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='material_usage_paths',
            field=models.FileField(blank=True, upload_to='', verbose_name='材料使用量文件路径'),
        ),
    ]
