# Generated by Django 2.0 on 2018-01-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordination', '0002_auto_20180118_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='construction_paper_paths',
            field=models.TextField(blank=True, verbose_name='施工图纸文件路径'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='design_material_paths',
            field=models.TextField(blank=True, verbose_name='设计材料单文件路径'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='design_paper_paths',
            field=models.TextField(blank=True, verbose_name='设计图纸文件路径'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='material_usage_paths',
            field=models.TextField(blank=True, verbose_name='材料使用量文件路径'),
        ),
    ]
