# Generated by Django 2.0 on 2018-01-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('internal_no', models.CharField(blank=True, max_length=100, unique=True, verbose_name='内部文号')),
                ('pro_no', models.CharField(blank=True, max_length=100, verbose_name='项目编号')),
                ('task_code', models.CharField(blank=True, max_length=100, verbose_name='任务编码')),
                ('pro_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('predict', models.CharField(max_length=100, verbose_name='预计信息点')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedCo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='挂靠单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目类型')),
            ],
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.District'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='linked_co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.LinkedCo'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='pro_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.ProjectType'),
        ),
    ]
