# Generated by Django 2.0 on 2018-01-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='linkedco',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='projecttype',
            old_name='name',
            new_name='text',
        ),
    ]
