# Generated by Django 2.0 on 2018-01-12 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0002_auto_20180111_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='信息创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='信息更新时间'),
        ),
    ]
