# Generated by Django 2.0 on 2018-01-22 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0003_auto_20180112_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='信息创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='district',
            name='memo',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='district',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='信息更新时间'),
        ),
        migrations.AddField(
            model_name='linkedco',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='信息创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedco',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='linkedco',
            name='memo',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='linkedco',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='信息更新时间'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='信息创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='memo',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='信息更新时间'),
        ),
    ]
